//
// Generated file, do not edit! Created by opp_msgtool 6.1 from GbnPacket.msg.
//

#ifndef __GBNPACKET_M_H
#define __GBNPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class GbnPacket;
// cplusplus {{
#include <omnetpp.h>
// }}

/**
 * Class generated from <tt>GbnPacket.msg:6</tt> by opp_msgtool.
 * <pre>
 * class GbnPacket extends cPacket
 * {
 *     int kind;
 *     int sequenceNumber;
 *     int ackNumber;
 *     int windowSize;
 *     bool hasError;
 * }
 * </pre>
 */
class GbnPacket : public ::omnetpp::cPacket
{
  protected:
    int kind = 0;
    int sequenceNumber = 0;
    int ackNumber = 0;
    int windowSize = 0;
    bool hasError = false;

  private:
    void copy(const GbnPacket& other);

  protected:
    bool operator==(const GbnPacket&) = delete;

  public:
    GbnPacket(const char *name=nullptr);
    GbnPacket(const GbnPacket& other);
    virtual ~GbnPacket();
    GbnPacket& operator=(const GbnPacket& other);
    virtual GbnPacket *dup() const override {return new GbnPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getKind() const;
    virtual void setKind(int kind);

    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);

    virtual int getAckNumber() const;
    virtual void setAckNumber(int ackNumber);

    virtual int getWindowSize() const;
    virtual void setWindowSize(int windowSize);

    virtual bool getHasError() const;
    virtual void setHasError(bool hasError);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const GbnPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, GbnPacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline GbnPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<GbnPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __GBNPACKET_M_H

